context:
  title: <span class="block xl:inline">Join the</span><span class="block text-blue-500 xl:inline">Talent Provider</span><span class="block xl:inline">Community</span>
  body: Share resources and connect with other organizations for partnership and collaboration opportunities.<br>Fill out our 5 minute profiling survey to access your customized resources.
  button:
    primary:
      href: '#'
      label: Get started
  image:
    handle: image
    context:
      src: https://images.unsplash.com/photo-1520333789090-1afc82db536a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2102&q=80